# Generated by Django 4.2.28 on 2026-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_id', models.CharField(max_length=10)),
                ('paciente', models.CharField(max_length=200)),
                ('destino', models.CharField(choices=[('PISO', 'Piso'), ('UTI', 'UTI'), ('UTIM', 'UTIM')], max_length=10)),
                ('timestamp_ingreso', models.DateTimeField()),
                ('timestamp_egreso', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de Egreso',
                'verbose_name_plural': 'Eventos de Egreso',
                'ordering': ['-timestamp_egreso'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('cama', 'Cama'), ('consultorio', 'Consultorio'), ('shock', 'Shock Room'), ('aislamiento', 'Aislamiento')], max_length=20)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('LIMPIEZA', 'En Limpieza'), ('RESERVADO', 'Reservado'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='LIBRE', max_length=20)),
                ('timestamp_estado', models.DateTimeField(auto_now=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['id'],
            },
        ),
    ]
