# Generated by Django 4.2.28 on 2026-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='destino_solicitado',
            field=models.CharField(blank=True, choices=[('PISO', 'Piso'), ('UTI', 'UTI'), ('UTIM', 'UTIM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='timestamp_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
