# Generated by Django 6.0.7 on 2026-08-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardia', '0002_posicion_destino_solicitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='destino_asignado',
            field=models.CharField(blank=True, choices=[('PISO', 'Piso'), ('UTI', 'UTI'), ('UTIM', 'UTIM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='timestamp_destino_asignado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
