# Generated by Django 6.0.7 on 2026-09-13 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardia', '0003_posicion_destino_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoegreso',
            name='cama_asignada_detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventoegreso',
            name='duracion_espera_cama',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoegreso',
            name='duracion_total_guardia',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoegreso',
            name='timestamp_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoegreso',
            name='timestamp_solicitud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='cama_asignada_detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='etapa_circuito',
            field=models.CharField(choices=[('ATENCION', 'En Atención'), ('SOLICITADA', 'Cama Solicitada'), ('ASIGNADA', 'Cama Asignada')], default='ATENCION', max_length=20),
        ),
        migrations.AddField(
            model_name='posicion',
            name='timestamp_solicitud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventoegreso',
            name='timestamp_egreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
